import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import Image from "next/image";

import type { RouterOutputs } from "~/utils/api";

import {
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
  useUser,
} from "@clerk/nextjs";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex w-full">
      <input
        placeholder="What's on your mind?!"
        className="grow bg-transparent"
      />
    </div>
  );
};
// ·
type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div key={post.id} className="flex gap-3 border-b border-slate-400 p-4">
      <Image
        alt={`@${author.username}'s profile picture`}
        src={author.profileImageUrl}
        className="h-8 w-8 rounded-full"
        height={32}
        width={32}
      />
      <div className="flex flex-col">
        <div className="flex gap-1 text-slate-300">
          <span>{`@${author.username}`}</span>
          <span className="font-thin">{`· ${dayjs(
            post.createdAt
          ).fromNow()}`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
};

export default function Home() {
  const { isLoaded, isSignedIn, user } = useUser();

  console.log(user);

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading</div>;

  if (!data) return <div>Something went wrong</div>;

  console.log(user);

  console.log("Hello");
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="border-b border-slate-400 p-4 ">
            <SignedIn>
              {/* Mount the UserButton component */}
              <div className="flex flex-row gap-3">
                <UserButton afterSignOutUrl="/" />
                <CreatePostWizard />
              </div>
            </SignedIn>
            <SignedOut>
              {/* Signed out users get sign in button */}
              <SignInButton />
            </SignedOut>
          </div>
          <div className="flex flex-col">
            {[...data, ...data]?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
